apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cozy-stack.fullname" . }}
  labels:
    {{- include "cozy-stack.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cozy-stack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cozy-stack.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cozy-stack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cozy-config
              mountpath: "/etc/cozy"
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: COUCHDB_HOST
              valueFrom:
                secretKeyRef:
                  name: "{{ template "couchdb.secret" . }}"
                  key: host
            - name: COUCHDB_PORT
              valueFrom:
                secretKeyRef:
                  name: "{{ template "couchdb.secret" . }}"
                  key: port
            - name: COUCHDB_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: "{{ template "couchdb.secret" . }}"
                  key: protocol
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ template "couchdb.secret" . }}"
                  key: user
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "couchdb.secret" . }}"
                  key: password
            - name: COZY_ADMIN_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: "{{ template "cozy.admin.secret" . }}"
                  key: passphrase
      volumes:
        - name: cozy-config
          secret:
            secretName: "{{ template "cozy.config.secret" }}"
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
