{{- if not .Values.couchdb.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
data:
  host: {{ .Values.couchdb.host | b64enc | quote }}
  port: {{ .Values.couchdb.port | b64enc | quote }}
  protocol: {{ .Values.couchdb.protocol | b64enc | quote }}
  user: {{ .Values.couchdb.user | b64enc | quote }}
  password: {{ .Values.couchdb.password | b64enc | quote }}
{{- end }}
