# Default values for cozy-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- how many pods to deploy of cozy
replicaCount: 1

image:
  # -- Set the registry for your docker image
  registry: docker.io
  # -- Set the repository for your cozy docker image.
  # Official production image is cozy/cozy-stack but it cannot run as non-root yet
  repository: jessebot/cozy-stack
  # -- set to Always if you're using the tag: "latest"
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- secrets to pull your docker private docker image
imagePullSecrets: []

# -- Overrides the name of this chart instead of using the release name everywhere
nameOverride: ""
# -- Overrides the full name of this chart instead of using the release name everywhere
fullnameOverride: ""

cozy:
  # -- cozy admin user's password. ignored if cozy.existingSecret is set
  adminPassphrase: ""
  # -- existing kubernetes secret containing a key called passphrase
  existingAdminSecret: ""
  # -- file system directory
  # see: https://github.com/cozy/cozy-stack/blob/0fe78134b2d09c73813be48274c66ed8582328e6/cozy.example.yaml#L64
  configPath: "/etc/cozy"
  # -- sharing domain for connecting iwth other cozy friends
  domain: ""
  # -- override the default cozy configuration with your own secret that will be mounted at {{ Values.cozy.configPath }}
  # must contain a key called cozy.yaml
  existingConfigSecret: ""

couchdb:
  # -- hostname of the couchdb server
  host: ""
  # -- port to connect to the database over
  port: "5984"
  # -- connect to couchdb with either http or https
  protocol: "http"
  # -- username to connect to couchdb with
  user: ""
  # -- password to connection to couchdb with
  password: ""
  # -- existing kubernetes secret with couchdb related secret keys:
  # "host", "user", "password", "protocol", "port"
  existingSecret: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "cozy"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  # -- group to chown volumes to. If using the production cozy/cozy-stack image, you may need to set this 0 to run as root
  fsGroup: 3552

securityContext:
  # -- runAsUser for the cozy container. If using the production cozy/cozy-stack image, you may need to set this 0 to run as root
  runAsUser: 3552
  # -- runAsGroup for the cozy container. If using the production cozy/cozy-stack image, you may need to set this 0 to run as root
  runAsGroup: 3552
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true

service:
  type: ClusterIP
  # -- this is the target port on the container
  targetPort: 8080
  port: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  # for ingress hosts for cozy, you'll need an ingress per app, e.g.
  #   home.cozy.example.com, settings.cozy.example.com etc
  # learn more here: https://docs.cozy.io/en/tutorials/selfhosting/finalize/nginx/
  # if this is exposed to the internet/intranet make sure to also setup your DNS records like:
  #   cozy     1h     IN         A     <your_server_IP>
  #   *.cozy   1h     IN       CNAME     cozy
  #
  # example using example.com as the core domain:
  #   cozy.example.com     1h     IN         A       42.42.20.24
  #   *.cozy.example.com   1h     IN       CNAME     cozy
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
    #
    # - host: settings.chart-example.local
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
    #
    # - host: home.chart-example.local
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
    #
    # - host: drive.chart-example.local
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  #
  #  - secretName: settings-chart-example-tls
  #    hosts:
  #      - settings.chart-example.local
  #
  #  - secretName: home-chart-example-tls
  #    hosts:
  #      - home.chart-example.local
  #
  #  - secretName: drive-chart-example-tls
  #    hosts:
  #      - drive.chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Additional volumes on the output Deployment definition.
extraVolumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts on the output Deployment definition.
extraVolumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}


## Liveness and readiness probe values
##
livenessProbe:
  # -- enable liveness probes
  # Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 15
  successThreshold: 1

readinessProbe:
  # -- enable readiness probes
  # Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 15
  successThreshold: 1
